### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by vosybac** [activey/Skyrails#1]
Can you list all command of skyrails? I can find only two commands:
1. one--links->two
2. gl - group : one

Thank you.

**Comment by activey** [comment]
Sorry but I dont know much more ... You can take a look here for some tips https://github.com/activey/Skyrails/tree/master/skyrails-server/scripts

**Comment by vosybac** [comment]
I tried the two files in the script folder and use Google translate to translate from Polish to English and can understand the command :)

I have a new question?

Building a large graph manually take a lot of time, so I want to use client.py to automatically build large graph.

Can you help run the client.py on Window operating system?
I run it but nothing happen.
Thank you so much.
